import { createPlatformSnapshot } from "./platform-model.js";
import { LIVE_PLATFORM_ORIGIN } from "./platform-endpoints.js";
export const localDemoPlatformData = Object.freeze({
  seededDemo: true,
  user: Object.freeze({ userRef: "usr-demo-local", displayName: "Demo Platform User", email: "demo@platform.local", status: "active" }),
  membership: Object.freeze({ membershipRef: "membership-demo", userRef: "usr-demo-local", workspaceRef: "workspace-demo", role: "owner", status: "active" }),
  workspace: Object.freeze({ workspaceRef: "workspace-demo", name: "Demo Workspace", businessDisplayName: "Platform Core Sandbox", status: "active" }),
  application: Object.freeze({ applicationRef: "application-demo", workspaceRef: "workspace-demo", name: "Demo LINE Platform", status: "active" }),
  integration: Object.freeze({ integrationRef: "integration-demo", workspaceRef: "workspace-demo", applicationRef: "application-demo", displayName: "Demo LINE OA", lineBotAccount: "@platformdemo", environment: "sandbox", note: "Seeded local demo only", status: "pending", updatedAt: 1785542400000 }),
  loginChannel: Object.freeze({ loginChannelRef: "login-demo", integrationRef: "integration-demo", workspaceRef: "workspace-demo", channelId: "100000001", callbackUrl: null, verificationStatus: "not_configured" }),
  messagingChannel: Object.freeze({ messagingChannelRef: "messaging-demo", integrationRef: "integration-demo", workspaceRef: "workspace-demo", channelId: "200000001", webhookUrl: `${LIVE_PLATFORM_ORIGIN}/webhook/oa-primary`, messagingVerification: "verified", webhookVerification: "verified" }),
  credentialReference: Object.freeze({ credentialReference: "cred-demo-reference", integrationRef: "integration-demo", workspaceRef: "workspace-demo", credentialStatus: "configured", updatedAt: 1785542400000 }),
  binding: Object.freeze({ bindingRef: "binding-demo", bindingKey: "oa-primary", integrationRef: "integration-demo", workspaceRef: "workspace-demo", applicationRef: "application-demo", provider: "LINE", status: "pending", overallStatus: "not_configured" }),
});
export function createLocalDemoSnapshot(session, user = localDemoPlatformData.user) {
  return createPlatformSnapshot({ users: [Object.freeze({ ...localDemoPlatformData.user, ...user, userRef: localDemoPlatformData.user.userRef, email: localDemoPlatformData.user.email })], memberships: [localDemoPlatformData.membership], workspaces: [localDemoPlatformData.workspace], applications: [localDemoPlatformData.application], lineIntegrations: [localDemoPlatformData.integration], loginChannels: [localDemoPlatformData.loginChannel], messagingChannels: [localDemoPlatformData.messagingChannel], credentialReferences: [localDemoPlatformData.credentialReference], channelBindings: [localDemoPlatformData.binding], featureEntitlements: [{ entitlementRef: "entitlement-demo", workspaceRef: "workspace-demo", featureKey: "line_integration", status: "included" }], verificationResults: [{ verificationRef: "verification-demo", integrationRef: "integration-demo", workspaceRef: "workspace-demo", loginStatus: "not_configured", messagingStatus: "verified", webhookStatus: "verified", overallStatus: "not_configured", checkedAt: 1785542400000 }], auditEvents: [{ auditRef: "audit-demo", workspaceRef: "workspace-demo", action: "demo_seed_loaded", result: "completed", occurredAt: 1785542400000 }], session, currentWorkspaceRef: "workspace-demo", currentBindingRef: "binding-demo" });
}
