import type { IntentDefinition, SlotDefinition } from "./models";

export const workbenchIntents: readonly IntentDefinition[] = Object.freeze([
  {
    intentKey: "event.create",
    displayName: "建立活動",
    moduleKey: "event_engine",
    operationKey: "event.create",
    intentVersion: 1,
    requiredPermission: "tenant:update",
    riskLevel: "high",
    requiredSlots: ["activity_name", "start_time", "end_time", "capacity"],
    optionalSlots: ["location"],
    confirmationPolicy: "explicit_confirmation",
    responseTemplateKey: "event.create",
    status: "active",
  },
  {
    intentKey: "event.registration_summary",
    displayName: "活動報名狀況",
    moduleKey: "event_engine",
    operationKey: "event.registration_summary",
    intentVersion: 1,
    requiredPermission: "tenant:read",
    riskLevel: "read",
    requiredSlots: ["event_reference"],
    optionalSlots: [],
    confirmationPolicy: "none",
    responseTemplateKey: "event.registration_summary",
    status: "active",
  },
  {
    intentKey: "event.list",
    displayName: "活動列表",
    moduleKey: "event_engine",
    operationKey: "event.list",
    intentVersion: 1,
    requiredPermission: "tenant:read",
    riskLevel: "read",
    requiredSlots: [],
    optionalSlots: [],
    confirmationPolicy: "none",
    responseTemplateKey: "event.list",
    status: "active",
  },
  {
    intentKey: "event.cancel",
    displayName: "取消活動",
    moduleKey: "event_engine",
    operationKey: "event.cancel",
    intentVersion: 1,
    requiredPermission: "tenant:update",
    riskLevel: "high",
    requiredSlots: ["event_reference"],
    optionalSlots: [],
    confirmationPolicy: "explicit_confirmation",
    responseTemplateKey: "event.cancel",
    status: "active",
  },
  {
    intentKey: "network.my_commission",
    displayName: "我的佣金",
    moduleKey: "business_network_engine",
    operationKey: "network.my_commission",
    intentVersion: 1,
    requiredPermission: "commission:read_self",
    riskLevel: "read",
    requiredSlots: [],
    optionalSlots: ["from", "until"],
    confirmationPolicy: "none",
    responseTemplateKey: "network.my_commission",
    status: "active",
  },
  {
    intentKey: "network.my_performance",
    displayName: "推薦業績",
    moduleKey: "business_network_engine",
    operationKey: "network.my_performance",
    intentVersion: 1,
    requiredPermission: "sales:read",
    riskLevel: "read",
    requiredSlots: [],
    optionalSlots: ["from", "until"],
    confirmationPolicy: "none",
    responseTemplateKey: "network.my_performance",
    status: "active",
  },
  {
    intentKey: "network.my_referrals",
    displayName: "我的推薦",
    moduleKey: "business_network_engine",
    operationKey: "network.my_referrals",
    intentVersion: 1,
    requiredPermission: "referral:read",
    riskLevel: "read",
    requiredSlots: [],
    optionalSlots: ["from", "until", "limit"],
    confirmationPolicy: "none",
    responseTemplateKey: "network.my_referrals",
    status: "active",
  },
  {
    intentKey: "module.list_available",
    displayName: "可用功能",
    moduleKey: "application_assembly",
    operationKey: "module.list_available",
    intentVersion: 1,
    requiredPermission: "module_catalog:read",
    riskLevel: "read",
    requiredSlots: [],
    optionalSlots: [],
    confirmationPolicy: "none",
    responseTemplateKey: "module.list_available",
    status: "active",
  },
  {
    intentKey: "module.enable",
    displayName: "啟用模組",
    moduleKey: "application_assembly",
    operationKey: "module.enable",
    intentVersion: 1,
    requiredPermission: "module_enablement:manage",
    riskLevel: "high",
    requiredSlots: ["module_reference"],
    optionalSlots: [],
    confirmationPolicy: "explicit_confirmation",
    responseTemplateKey: "module.enable",
    status: "active",
  },
  {
    intentKey: "module.disable",
    displayName: "停用模組",
    moduleKey: "application_assembly",
    operationKey: "module.disable",
    intentVersion: 1,
    requiredPermission: "module_enablement:manage",
    riskLevel: "high",
    requiredSlots: ["module_reference"],
    optionalSlots: [],
    confirmationPolicy: "explicit_confirmation",
    responseTemplateKey: "module.disable",
    status: "active",
  },
  {
    intentKey: "diagnostics.today_summary",
    displayName: "今日系統異常",
    moduleKey: "platform_observability",
    operationKey: "diagnostics.today_summary",
    intentVersion: 1,
    requiredPermission: "diagnostics:read_tenant",
    riskLevel: "read",
    requiredSlots: [],
    optionalSlots: [],
    confirmationPolicy: "none",
    responseTemplateKey: "diagnostics.today_summary",
    status: "active",
  },
  {
    intentKey: "diagnostics.lookup_support_code",
    displayName: "查詢支援碼",
    moduleKey: "platform_observability",
    operationKey: "diagnostics.lookup_support_code",
    intentVersion: 1,
    requiredPermission: "diagnostics:read_tenant",
    riskLevel: "read",
    requiredSlots: ["support_code"],
    optionalSlots: [],
    confirmationPolicy: "none",
    responseTemplateKey: "diagnostics.lookup_support_code",
    status: "active",
  },
]);

export const slotDefinitions: Readonly<Record<string, SlotDefinition>> =
  Object.freeze({
    activity_name: {
      slotKey: "activity_name",
      type: "string",
      label: "活動名稱",
      required: true,
      maximumLength: 160,
    },
    start_time: {
      slotKey: "start_time",
      type: "datetime",
      label: "開始時間",
      required: true,
      minimum: 0,
    },
    end_time: {
      slotKey: "end_time",
      type: "datetime",
      label: "結束時間",
      required: true,
      minimum: 0,
    },
    capacity: {
      slotKey: "capacity",
      type: "integer",
      label: "名額",
      required: true,
      minimum: 1,
      maximum: 100000,
    },
    location: {
      slotKey: "location",
      type: "string",
      label: "地點",
      required: false,
      maximumLength: 300,
    },
    event_reference: {
      slotKey: "event_reference",
      type: "string",
      label: "活動編號",
      required: true,
      maximumLength: 120,
    },
    module_reference: {
      slotKey: "module_reference",
      type: "module_reference",
      label: "模組",
      required: true,
      maximumLength: 80,
      values: ["event_engine", "business_network_engine"],
    },
    support_code: {
      slotKey: "support_code",
      type: "support_code",
      label: "支援碼",
      required: true,
      maximumLength: 32,
    },
    from: {
      slotKey: "from",
      type: "datetime",
      label: "起始時間",
      required: false,
      minimum: 0,
    },
    until: {
      slotKey: "until",
      type: "datetime",
      label: "結束時間",
      required: false,
      minimum: 0,
    },
    limit: {
      slotKey: "limit",
      type: "integer",
      label: "筆數",
      required: false,
      minimum: 1,
      maximum: 50,
    },
  });

export function getIntent(intentKey: string): IntentDefinition | null {
  return (
    workbenchIntents.find(
      (value) => value.intentKey === intentKey && value.status === "active",
    ) ?? null
  );
}
