import { canonicalJson, sha256Hex } from "../persistence/crypto";
import { assertDataHandling, assertHardCeiling, assertKillSwitch } from "./policy";
import { ProviderGovernanceError, type DataSensitivity, type HardCeiling, type HardCeilingUsage, type KillSwitchScope, type KillSwitchState, type ProviderDataPolicy, type ProviderEnvironment, type ProviderGovernanceGate, type ProviderLifecycleState, type ProviderReadinessSnapshot, type ProviderRouteGovernanceRequest } from "./models";

interface IdempotencyRow { request_fingerprint: string; stored_result_json: string; }
interface EnablementRow { id: string; lifecycle_state: ProviderLifecycleState; lifecycle_version: number; }
interface KillSwitchRow { id: string; scope_type: KillSwitchScope; state: KillSwitchState; version: number; }

export class AiProviderGovernanceRepository implements ProviderGovernanceGate {
  constructor(private readonly db: D1Database) {}

  getIdempotency(operation: string, keyHash: string) {
    return this.db.prepare("SELECT request_fingerprint,stored_result_json FROM idempotency_records WHERE scope_type='platform' AND operation=?1 AND idempotency_key_hash=?2 AND status='completed'").bind(operation, keyHash).first<IdempotencyRow>();
  }

  currentEnablement(providerKey: string, providerVersion: string, environment: ProviderEnvironment) {
    return this.db.prepare("SELECT id,lifecycle_state,lifecycle_version FROM ai_provider_enablements WHERE provider_key=?1 AND provider_version=?2 AND environment=?3 ORDER BY lifecycle_version DESC LIMIT 1").bind(providerKey, providerVersion, environment).first<EnablementRow>();
  }

  async insertEnablement(values: { id: string; providerKey: string; providerVersion: string; environment: ProviderEnvironment; state: ProviderLifecycleState; version: number; actor: string; reason: string; evidence: readonly string[]; idempotencyId: string; auditId: string; operation: string; keyHash: string; fingerprint: string; storedResult: Readonly<Record<string, unknown>>; correlationId: string; now: number }): Promise<void> {
    await this.db.batch([
      this.db.prepare("INSERT INTO idempotency_records(id,scope_type,tenant_id,operation,idempotency_key_hash,request_fingerprint,status,stored_result_json,result_code,processing_owner,generation,lease_expires_at,started_at,completed_at,expires_at,created_at,updated_at) VALUES(?1,'platform',NULL,?2,?3,?4,'completed',?5,'AI_PROVIDER_GOVERNANCE_CHANGED',NULL,1,NULL,?6,?6,?7,?6,?6)").bind(values.idempotencyId, values.operation, values.keyHash, values.fingerprint, JSON.stringify(values.storedResult), values.now, values.now + 86_400_000),
      this.db.prepare("INSERT INTO audit_records(id,scope_type,tenant_id,actor_type,actor_reference,action,resource_type,resource_reference,decision,reason_code,correlation_reference,occurred_at,created_at) VALUES(?1,'platform',NULL,'platform_operator',?2,'ai.provider_enablement_changed','ai_provider',?3,'changed',?4,?5,?6,?6)").bind(values.auditId, values.actor, `${values.providerKey}:${values.environment}`, values.reason, values.correlationId, values.now),
      this.db.prepare("INSERT INTO ai_provider_enablements(id,provider_key,provider_version,environment,lifecycle_state,lifecycle_version,actor_reference,permission_key,reason_code,evidence_references_json,idempotency_record_id,audit_record_id,created_at) VALUES(?1,?2,?3,?4,?5,?6,?7,'ai_provider_enablement:manage',?8,?9,?10,?11,?12)").bind(values.id, values.providerKey, values.providerVersion, values.environment, values.state, values.version, values.actor, values.reason, JSON.stringify(values.evidence), values.idempotencyId, values.auditId, values.now),
    ]);
  }

  currentKillSwitch(environment: ProviderEnvironment, scopeType: KillSwitchScope, scopeKey: string) {
    return this.db.prepare("SELECT id,scope_type,state,version FROM ai_provider_kill_switches WHERE environment=?1 AND scope_type=?2 AND scope_key=?3 ORDER BY version DESC LIMIT 1").bind(environment, scopeType, scopeKey).first<KillSwitchRow>();
  }

  async insertKillSwitch(values: { id: string; environment: ProviderEnvironment; scopeType: KillSwitchScope; scopeKey: string; providerKey?: string; modelKey?: string; taskKey?: string; tenantId?: string; applicationId?: string; state: KillSwitchState; version: number; reason: string; actor: string; idempotencyId: string; auditId: string; operation: string; keyHash: string; fingerprint: string; storedResult: Readonly<Record<string, unknown>>; correlationId: string; now: number }): Promise<void> {
    await this.db.batch([
      this.db.prepare("INSERT INTO idempotency_records(id,scope_type,tenant_id,operation,idempotency_key_hash,request_fingerprint,status,stored_result_json,result_code,processing_owner,generation,lease_expires_at,started_at,completed_at,expires_at,created_at,updated_at) VALUES(?1,'platform',NULL,?2,?3,?4,'completed',?5,'AI_PROVIDER_KILL_SWITCH_CHANGED',NULL,1,NULL,?6,?6,?7,?6,?6)").bind(values.idempotencyId, values.operation, values.keyHash, values.fingerprint, JSON.stringify(values.storedResult), values.now, values.now + 86_400_000),
      this.db.prepare("INSERT INTO audit_records(id,scope_type,tenant_id,actor_type,actor_reference,action,resource_type,resource_reference,decision,reason_code,correlation_reference,occurred_at,created_at) VALUES(?1,'platform',NULL,'platform_operator',?2,'ai.provider_kill_switch_changed','ai_kill_switch',?3,'changed',?4,?5,?6,?6)").bind(values.auditId, values.actor, `${values.environment}:${values.scopeKey}`, values.reason, values.correlationId, values.now),
      this.db.prepare("INSERT INTO ai_provider_kill_switches(id,environment,scope_type,scope_key,provider_key,model_key,task_key,tenant_id,application_id,state,version,reason_code,actor_reference,idempotency_record_id,audit_record_id,created_at) VALUES(?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,?11,?12,?13,?14,?15,?16)").bind(values.id, values.environment, values.scopeType, values.scopeKey, values.providerKey ?? null, values.modelKey ?? null, values.taskKey ?? null, values.tenantId ?? null, values.applicationId ?? null, values.state, values.version, values.reason, values.actor, values.idempotencyId, values.auditId, values.now),
    ]);
  }

  async readinessSnapshot(providerKey: string, providerVersion: string, environment: ProviderEnvironment, taskKey: string, now: number): Promise<ProviderReadinessSnapshot> {
    if (providerKey === "deterministic_local_adapter") return { providerKey, providerVersion, environment, external: false, lifecycle: null, complianceStatus: null, complianceExpiresAt: null, dataPolicyActive: true, secretStatus: null, matrixMode: "shadow_only", hardCeilingActive: true, killSwitchState: "enabled", observabilityReady: true, usageEvidenceReady: true, shadowPlanStatus: "approved", shadowPlanExpiresAt: now + 1, canaryPlanStatus: "draft", rollbackPlanReady: true, incidentRunbookReady: true, ownerAssigned: true, approvalsSeparated: true, now };
    const [enablement, compliance, policy, secret, matrix, ceiling, platformSwitch, shadow, canary, rollback, runbooks, approvals] = await Promise.all([
      this.currentEnablement(providerKey, providerVersion, environment),
      this.db.prepare("SELECT compliance_status,expires_at FROM ai_provider_compliance_profiles WHERE provider_key=?1 AND provider_version=?2 AND environment=?3 ORDER BY profile_version DESC LIMIT 1").bind(providerKey, providerVersion, environment).first<{ compliance_status: ProviderReadinessSnapshot["complianceStatus"]; expires_at: number }>(),
      this.db.prepare("SELECT status FROM ai_provider_data_policies WHERE provider_key=?1 AND provider_version=?2 AND environment=?3 ORDER BY policy_version DESC LIMIT 1").bind(providerKey, providerVersion, environment).first<{ status: string }>(),
      this.db.prepare("SELECT status FROM ai_provider_secret_references WHERE provider_key=?1 AND environment=?2 ORDER BY version DESC LIMIT 1").bind(providerKey, environment).first<{ status: ProviderReadinessSnapshot["secretStatus"] }>(),
      this.db.prepare("SELECT enablement_mode FROM ai_task_provider_allow_matrix WHERE provider_key=?1 AND provider_version=?2 AND task_key=?3 AND environment=?4 AND status='active' LIMIT 1").bind(providerKey, providerVersion, taskKey, environment).first<{ enablement_mode: ProviderReadinessSnapshot["matrixMode"] }>(),
      this.db.prepare("SELECT status FROM ai_provider_hard_ceilings WHERE provider_key=?1 AND environment=?2 ORDER BY version DESC LIMIT 1").bind(providerKey, environment).first<{ status: string }>(),
      this.currentKillSwitch(environment, "platform", "platform"),
      this.db.prepare("SELECT status,expires_at FROM ai_shadow_plans WHERE provider_key=?1 AND task_key=?2 AND environment=?3 ORDER BY version DESC LIMIT 1").bind(providerKey, taskKey, environment).first<{ status: ProviderReadinessSnapshot["shadowPlanStatus"]; expires_at: number }>(),
      this.db.prepare("SELECT status FROM ai_canary_plans WHERE provider_key=?1 AND task_key=?2 AND environment=?3 ORDER BY version DESC LIMIT 1").bind(providerKey, taskKey, environment).first<{ status: "draft" }>(),
      this.db.prepare("SELECT owner FROM ai_provider_rollback_plans WHERE provider_key=?1 AND environment=?2 AND status='approved' ORDER BY version DESC LIMIT 1").bind(providerKey, environment).first<{ owner: string }>(),
      this.db.prepare("SELECT count(DISTINCT incident_type) count FROM ai_provider_incident_runbooks WHERE provider_key=?1 AND environment=?2 AND status='approved'").bind(providerKey, environment).first<{ count: number }>(),
      this.db.prepare("SELECT count(DISTINCT reviewer_role) roles FROM ai_provider_approval_records WHERE provider_key=?1 AND provider_version=?2 AND environment=?3 AND decision='approved' AND expires_at>?4").bind(providerKey, providerVersion, environment, now).first<{ roles: number }>(),
    ]);
    return { providerKey, providerVersion, environment, external: true, lifecycle: enablement?.lifecycle_state ?? null, complianceStatus: compliance?.compliance_status ?? null, complianceExpiresAt: compliance?.expires_at ?? null, dataPolicyActive: policy?.status === "active", secretStatus: secret?.status ?? null, matrixMode: matrix?.enablement_mode ?? null, hardCeilingActive: ceiling?.status === "active", killSwitchState: platformSwitch?.state ?? "enabled", observabilityReady: true, usageEvidenceReady: true, shadowPlanStatus: shadow?.status ?? null, shadowPlanExpiresAt: shadow?.expires_at ?? null, canaryPlanStatus: canary?.status ?? null, rollbackPlanReady: Boolean(rollback), incidentRunbookReady: (runbooks?.count ?? 0) >= 4, ownerAssigned: Boolean(rollback?.owner), approvalsSeparated: (approvals?.roles ?? 0) >= 3, now };
  }

  async authorize(request: ProviderRouteGovernanceRequest): Promise<void> {
    try {
      const switches = (await this.db.prepare(`SELECT scope_type,state FROM ai_provider_kill_switches k WHERE environment=?1 AND version=(SELECT max(k2.version) FROM ai_provider_kill_switches k2 WHERE k2.environment=k.environment AND k2.scope_type=k.scope_type AND k2.scope_key=k.scope_key) AND ((scope_type='platform' AND scope_key='platform') OR (scope_type='environment' AND scope_key=?1) OR (scope_type='provider' AND provider_key=?2) OR (scope_type='model' AND provider_key=?2 AND model_key=?3) OR (scope_type='task' AND task_key=?4) OR (scope_type='provider_task' AND provider_key=?2 AND task_key=?4) OR (scope_type='tenant' AND tenant_id=?5) OR (scope_type='application' AND tenant_id=?5 AND application_id=?6)) ORDER BY CASE scope_type WHEN 'platform' THEN 1 WHEN 'environment' THEN 2 WHEN 'provider' THEN 3 WHEN 'model' THEN 4 WHEN 'provider_task' THEN 5 WHEN 'task' THEN 6 WHEN 'tenant' THEN 7 ELSE 8 END`).bind(request.environment, request.providerKey, request.modelKey, request.taskKey, request.tenantId, request.applicationId).all<{ scope_type: string; state: KillSwitchState }>()).results;
      for (const item of switches) assertKillSwitch(item.state, item.scope_type, request.interactive);
      if (request.providerKey === "deterministic_local_adapter") return;
      const enablement = await this.currentEnablement(request.providerKey, request.modelVersion, request.environment);
      if (enablement?.lifecycle_state !== "approved_for_shadow") throw new ProviderGovernanceError("AI_PROVIDER_LIFECYCLE_INVALID");
      const compliance = await this.db.prepare("SELECT processing_regions_json,retention_days,deletion_support,compliance_status,expires_at FROM ai_provider_compliance_profiles WHERE provider_key=?1 AND provider_version=?2 AND environment=?3 ORDER BY profile_version DESC LIMIT 1").bind(request.providerKey, request.modelVersion, request.environment).first<{ processing_regions_json: string; retention_days: number; deletion_support: number; compliance_status: string; expires_at: number }>();
      if (!compliance || compliance.compliance_status !== "approved" || compliance.expires_at <= Date.now()) throw new ProviderGovernanceError("AI_PROVIDER_COMPLIANCE_REQUIRED");
      const policyRow = await this.db.prepare("SELECT allowed_sensitivity,allow_prompt_retention,allow_provider_training,allow_cross_region,require_zero_retention,require_regional_processing,require_deletion_capability,maximum_retention_days,redaction_required,structured_output_required FROM ai_provider_data_policies WHERE provider_key=?1 AND provider_version=?2 AND environment=?3 AND status='active' ORDER BY policy_version DESC LIMIT 1").bind(request.providerKey, request.modelVersion, request.environment).first<Record<string, number | string>>();
      if (!policyRow) throw new ProviderGovernanceError("AI_PROVIDER_DATA_POLICY_DENIED");
      const policy: ProviderDataPolicy = { allowedSensitivity: policyRow.allowed_sensitivity as ProviderDataPolicy["allowedSensitivity"], allowPromptRetention: policyRow.allow_prompt_retention === 1, allowProviderTraining: policyRow.allow_provider_training === 1, allowCrossRegion: policyRow.allow_cross_region === 1, requireZeroRetention: policyRow.require_zero_retention === 1, requireRegionalProcessing: policyRow.require_regional_processing === 1, requireDeletionCapability: policyRow.require_deletion_capability === 1, maximumRetentionDays: Number(policyRow.maximum_retention_days), redactionRequired: policyRow.redaction_required === 1, structuredOutputRequired: policyRow.structured_output_required === 1 };
      assertDataHandling({ taskSensitivity: request.sensitivity, inputSensitivity: request.sensitivity, policy, complianceRetentionDays: compliance.retention_days, regionMatches: JSON.parse(compliance.processing_regions_json).includes(request.environment === "production" ? "approved-region" : "local"), deletionSupported: compliance.deletion_support === 1 });
      const secret = await this.db.prepare("SELECT status FROM ai_provider_secret_references WHERE provider_key=?1 AND environment=?2 ORDER BY version DESC LIMIT 1").bind(request.providerKey, request.environment).first<{ status: string }>();
      if (secret?.status !== "active_future") throw new ProviderGovernanceError("AI_PROVIDER_SECRET_NOT_READY");
      const matrix = await this.db.prepare("SELECT maximum_input_units,maximum_output_units,maximum_estimated_cost_micros FROM ai_task_provider_allow_matrix WHERE provider_key=?1 AND provider_version=?2 AND model_key=?3 AND model_version=?4 AND task_key=?5 AND task_version=?6 AND environment=?7 AND enablement_mode='shadow_only' AND status='active'").bind(request.providerKey, request.modelVersion, request.modelKey, request.modelVersion, request.taskKey, request.taskVersion, request.environment).first<{ maximum_input_units: number; maximum_output_units: number; maximum_estimated_cost_micros: number }>();
      if (!matrix || request.inputUnits > matrix.maximum_input_units || request.outputUnits > matrix.maximum_output_units || request.estimatedCostMicros > matrix.maximum_estimated_cost_micros) throw new ProviderGovernanceError("AI_PROVIDER_MATRIX_DENIED");
      const ceilingRow = await this.db.prepare("SELECT maximum_requests_per_day,maximum_estimated_cost_micros_per_day,maximum_premium_requests_per_day,maximum_concurrent_requests,maximum_input_units_per_request,maximum_output_units_per_request,pricing_version FROM ai_provider_hard_ceilings WHERE provider_key=?1 AND environment=?2 AND status='active' ORDER BY version DESC LIMIT 1").bind(request.providerKey, request.environment).first<Record<string, number | string>>();
      if (!ceilingRow) throw new ProviderGovernanceError("AI_HARD_CEILING_EXCEEDED");
      const usageRow = await this.db.prepare("SELECT count(*) requests,coalesce(sum(estimated_cost_micros),0) cost FROM ai_usage_records WHERE provider_key=?1 AND occurred_at>=?2").bind(request.providerKey, Math.floor(Date.now() / 86_400_000) * 86_400_000).first<{ requests: number; cost: number }>();
      const active = await this.db.prepare("SELECT count(*) count FROM ai_budget_leases l JOIN ai_request_records r ON r.tenant_id=l.tenant_id AND r.id=l.request_id WHERE l.status='active' AND r.selected_provider_key=?1").bind(request.providerKey).first<{ count: number }>();
      const ceiling: HardCeiling = { maximumRequestsPerDay: Number(ceilingRow.maximum_requests_per_day), maximumEstimatedCostMicrosPerDay: Number(ceilingRow.maximum_estimated_cost_micros_per_day), maximumPremiumRequestsPerDay: Number(ceilingRow.maximum_premium_requests_per_day), maximumConcurrentRequests: Number(ceilingRow.maximum_concurrent_requests), maximumInputUnitsPerRequest: Number(ceilingRow.maximum_input_units_per_request), maximumOutputUnitsPerRequest: Number(ceilingRow.maximum_output_units_per_request), pricingVersion: String(ceilingRow.pricing_version) };
      const usage: HardCeilingUsage = { requestsToday: usageRow?.requests ?? 0, estimatedCostMicrosToday: usageRow?.cost ?? 0, premiumRequestsToday: 0, concurrentRequests: active?.count ?? 0 };
      assertHardCeiling(ceiling, usage, { inputUnits: request.inputUnits, outputUnits: request.outputUnits, estimatedCostMicros: request.estimatedCostMicros, premium: false });
    } catch (error) {
      if (error instanceof ProviderGovernanceError) throw error;
      throw new ProviderGovernanceError("AI_PROVIDER_GOVERNANCE_UNAVAILABLE");
    }
  }

  async evidenceDigest(value: unknown): Promise<string> { return sha256Hex(canonicalJson(value)); }
}
