import { env } from "cloudflare:workers";
import { applyD1Migrations,reset,type D1Migration } from "cloudflare:test";
import { beforeEach,describe,expect,it } from "vitest";
import { AiGatewayRepository } from "../../src/ai-gateway/repository";
import { AiGatewayService } from "../../src/ai-gateway/application";
import { createLocalAiProviderCatalog } from "../../src/ai-gateway/adapters";
import { DisabledAiGatewayObservationAdapter } from "../../src/ai-gateway/ports";
import type { UuidV7 } from "../../src/core/uuidv7";

const migrations=env.TEST_MIGRATIONS as readonly D1Migration[];let n=900000;
class Ids implements UuidV7{generate(){n+=1;return`019f0000-0000-7000-8000-${String(n).padStart(12,"0")}`;}}
const tenant="019f0000-0000-7000-8000-000000009001",user="019f0000-0000-7000-8000-000000009002",member="019f0000-0000-7000-8000-000000009003",app="019f0000-0000-7000-8000-000000009004",budget="019f0000-0000-7000-8000-000000009005";
const context={source:"trusted_runtime_context" as const,tenantId:tenant,applicationId:app,actorMembershipId:member,correlationId:"corr",permissionGranted:true,moduleEnabled:true,trafficAdmitted:true};
const input=(key="request-key",text="hello")=>({context,taskKey:"content.translation" as const,taskVersion:1 as const,input:{text},idempotencyKey:key,locale:"zh-TW",qualityTier:"standard" as const,cacheDirective:"allow" as const,requestedOutputUnits:100,requestedCostMicros:0});
async function seed(){await reset();await applyD1Migrations(env.DB,[...migrations]);await env.DB.batch([
 env.DB.prepare("INSERT INTO platform_users(id,status,created_at,updated_at) VALUES(?1,'active',1,1)").bind(user),
 env.DB.prepare("INSERT INTO tenants(id,name,status,created_at,updated_at) VALUES(?1,'AI Tenant','active',1,1)").bind(tenant),
 env.DB.prepare("INSERT INTO tenant_memberships(id,tenant_id,platform_user_id,status,join_source,joined_at,created_at,updated_at) VALUES(?1,?2,?3,'active','test',1,1,1)").bind(member,tenant,user),
 env.DB.prepare("INSERT INTO applications(id,tenant_id,application_key,name,status,default_locale,version,created_at,updated_at) VALUES(?1,?2,'ai-app','AI App','active','zh-TW',1,1,1)").bind(app,tenant),
 env.DB.prepare("INSERT INTO ai_budgets(id,scope_type,scope_key,tenant_id,application_id,window_key,window_started_at,window_ends_at,max_requests,max_input_units,max_output_units,max_cost_micros,max_concurrent,status,version,created_at,updated_at) VALUES(?1,'application','application:'||?2||':'||?3,?2,?3,'day',1,9999999999999,20,10000,10000,10000,2,'active',1,1,1)").bind(budget,tenant,app),
]);return new AiGatewayService(new AiGatewayRepository(env.DB),new Ids(),createLocalAiProviderCatalog(),new DisabledAiGatewayObservationAdapter(),()=>1000);}
beforeEach(async()=>{n=900000;await seed();});

describe("AI Gateway local D1",()=>{
 it("installs all AI tables and permissions with clean foreign keys",async()=>{const tables=await env.DB.prepare("SELECT count(*) count FROM sqlite_master WHERE type='table' AND name LIKE 'ai_%'").first<{count:number}>();const permissions=await env.DB.prepare("SELECT count(*) count FROM permissions WHERE permission_key LIKE 'ai_%'").first<{count:number}>();expect([tables?.count,permissions?.count]).toEqual([22,25]);expect((await env.DB.prepare("PRAGMA foreign_key_check").all()).results).toEqual([]);});
 it("executes task through budget, route, provider, validation and immutable usage",async()=>{const service=await seed();const result=await service.execute(input());expect(result.output).toEqual({text:"[zh-TW] hello"});expect(await service.listUsageSummary(context)).toEqual({requests:1,inputUnits:5,outputUnits:24,estimatedCostMicros:0});expect(await env.DB.prepare("SELECT route_policy_id,route_policy_version FROM ai_usage_records WHERE tenant_id=?1").bind(tenant).first()).toMatchObject({route_policy_id:"019f0000-0000-7000-8000-000000000825",route_policy_version:1});await expect(env.DB.prepare("DELETE FROM ai_usage_records").run()).rejects.toThrow(/ai_usage_immutable/);});
 it("replays same key and rejects a different fingerprint",async()=>{const service=await seed();const first=await service.execute(input());expect((await service.execute(input())).requestId).toBe(first.requestId);await expect(service.execute(input("request-key","different"))).rejects.toMatchObject({code:"AI_IDEMPOTENCY_CONFLICT"});expect((await service.listUsageSummary(context)).requests).toBe(1);});
 it("accounts for cache hits without a duplicate provider effect",async()=>{const service=await seed();await service.execute(input("cache-first"));const hit=await service.execute(input("cache-second"));expect(hit.cacheOutcome).toBe("hit");expect((await service.listUsageSummary(context)).requests).toBe(2);});
 it("enforces trusted context, traffic, module, and permission before persistence",async()=>{const service=await seed();for(const override of [{trafficAdmitted:false},{moduleEnabled:false},{permissionGranted:false}])await expect(service.prepareAiRequest({...input(),context:{...context,...override}})).rejects.toBeInstanceOf(Error);expect((await env.DB.prepare("SELECT count(*) count FROM ai_request_records").first<{count:number}>())?.count).toBe(0);});
 it("isolates tenant-scoped lookup",async()=>{const repository=new AiGatewayRepository(env.DB);expect(await repository.usageSummary("019f0000-0000-7000-8000-999999999999",app)).toEqual({requests:0,inputUnits:0,outputUnits:0,estimatedCostMicros:0});});
 it("cannot bind another tenant to a trusted application",async()=>{const service=await seed();await expect(service.prepareAiRequest({...input("cross-tenant"),context:{...context,tenantId:"019f0000-0000-7000-8000-999999999999"}})).rejects.toThrow();});
 it("isolates observability failure from a completed request",async()=>{const service=new AiGatewayService(new AiGatewayRepository(env.DB),new Ids(),createLocalAiProviderCatalog(),{record:async()=>{throw new Error("sidecar");}},()=>1000);await expect(service.execute(input("observation-failure"))).resolves.toMatchObject({cacheOutcome:"miss"});});
 it("selects one exact budget winner and rejects exhaustion",async()=>{const service=await seed();await env.DB.prepare("UPDATE ai_budgets SET max_requests=1,version=version+1,updated_at=2 WHERE id=?1").bind(budget).run();await service.execute(input("winner-1"));await expect(service.execute(input("winner-2"))).rejects.toMatchObject({code:"AI_BUDGET_EXCEEDED"});});
 it("enforces Platform and Application budgets in one atomic claim",async()=>{const service=await seed();await env.DB.prepare("INSERT INTO ai_budgets(id,scope_type,scope_key,tenant_id,application_id,window_key,window_started_at,window_ends_at,max_requests,max_input_units,max_output_units,max_cost_micros,max_concurrent,status,version,created_at,updated_at) VALUES('019f0000-0000-7000-8000-000000009099','platform','platform',NULL,NULL,'day',1,9999999999999,0,10000,10000,10000,2,'active',1,1,1)").run();await expect(service.execute(input("platform-deny"))).rejects.toMatchObject({code:"AI_BUDGET_EXCEEDED"});expect((await env.DB.prepare("SELECT used_requests FROM ai_budgets WHERE id=?1").bind(budget).first<{used_requests:number}>())?.used_requests).toBe(0);});
 it("uses bounded indexed tenant queries",async()=>{const detail=(await env.DB.prepare("EXPLAIN QUERY PLAN SELECT id FROM ai_usage_records WHERE tenant_id=?1 AND application_id=?2 AND task_key=?3 ORDER BY occurred_at DESC,id DESC LIMIT 50").bind(tenant,app,"content.translation").all<{detail:string}>()).results.map(x=>x.detail).join(" ");expect(detail).toContain("idx_ai_usage_application_task");});
 it("keeps permission vocabulary immutable after migration",async()=>{await expect(env.DB.prepare("INSERT INTO permissions(id,permission_key,description,status,created_at,updated_at) VALUES('019f0000-0000-7000-8000-999999999999','ai:bad','bad','active',1,1)").run()).rejects.toThrow(/permission_vocabulary_immutable/);});
 it("does not automatically grant AI permissions",async()=>{expect((await env.DB.prepare("SELECT count(*) count FROM role_permissions rp JOIN permissions p ON p.id=rp.permission_id WHERE p.permission_key LIKE 'ai_%'").first<{count:number}>())?.count).toBe(0);});
 it("stores no prompt, raw input, or provider response column",async()=>{const columns=(await env.DB.prepare("PRAGMA table_info(ai_request_records)").all<{name:string}>()).results.map((row)=>row.name);expect(columns).toContain("input_digest");expect(columns.join(" ")).not.toMatch(/prompt|raw_input|provider_response/);const usageColumns=(await env.DB.prepare("PRAGMA table_info(ai_usage_records)").all<{name:string}>()).results.map((row)=>row.name);expect(usageColumns.join(" ")).not.toMatch(/prompt|response|secret|token/);});
 it("isolates cache entries by tenant",async()=>{const service=await seed();await service.execute(input("cache-scope"));const row=await env.DB.prepare("SELECT cache_key FROM ai_cache_entries LIMIT 1").first<{cache_key:string}>();expect(row).not.toBeNull();expect(await new AiGatewayRepository(env.DB).getCache("019f0000-0000-7000-8000-999999999999",app,row!.cache_key,1000)).toBeNull();});
 it("does not return expired cache entries",async()=>{const service=await seed();await service.execute(input("cache-expiry"));await env.DB.prepare("UPDATE ai_cache_entries SET status='expired',version=version+1,updated_at=2000 WHERE tenant_id=?1").bind(tenant).run();const row=await env.DB.prepare("SELECT cache_key FROM ai_cache_entries LIMIT 1").first<{cache_key:string}>();expect(await new AiGatewayRepository(env.DB).getCache(tenant,app,row!.cache_key,2000)).toBeNull();});
 it("fails closed on budget counter underflow",async()=>{await expect(env.DB.prepare("UPDATE ai_budgets SET concurrent_claims=-1,version=version+1,updated_at=2 WHERE id=?1").bind(budget).run()).rejects.toThrow();});
 it("reclaims abandoned leases with bounded idempotent expiry",async()=>{const service=await seed();const prepared=await service.prepareAiRequest(input("abandoned-lease"));await service.claimAiBudget(input("abandoned-lease"),prepared);const repository=new AiGatewayRepository(env.DB);expect(await repository.expireBudgetLeases(32000,10)).toBe(1);expect(await repository.expireBudgetLeases(32000,10)).toBe(0);expect(await env.DB.prepare("SELECT status FROM ai_budget_leases WHERE request_id=?1").bind(prepared.requestId).first()).toMatchObject({status:"expired"});expect(await env.DB.prepare("SELECT concurrent_claims FROM ai_budgets WHERE id=?1").bind(budget).first()).toMatchObject({concurrent_claims:0});});
 it("rejects stale completion after the fenced lease is released",async()=>{const service=await seed();const result=await service.execute(input("stale-completion"));await expect(new AiGatewayRepository(env.DB).complete({usageId:"019f0000-0000-7000-8000-000000999999",requestId:result.requestId,tenantId:tenant,applicationId:app,actorMembershipId:member,taskKey:"content.translation",route:{providerKey:"deterministic_local_adapter",modelKey:"deterministic-fixture",modelVersion:"1"},routePolicyId:"019f0000-0000-7000-8000-000000000825",routePolicyVersion:1,inputUnits:1,outputUnits:1,costMicros:0,cacheOutcome:"miss",latencyMs:1,result:{ok:true},now:2000})).rejects.toThrow(/AI_BUDGET_LEASE_MISSING/);});
});
