import { env } from "cloudflare:workers";
import { applyD1Migrations, reset, type D1Migration } from "cloudflare:test";
import { beforeEach, describe, expect, it } from "vitest";
const migrations=env.TEST_MIGRATIONS as readonly D1Migration[];
beforeEach(reset);
describe("Migration 0010 Channel Adapter Foundation",()=>{
  it("installs seven tables, twelve indexes, eighteen triggers and ten permissions",async()=>{await applyD1Migrations(env.DB,[...migrations]);const tables=await env.DB.prepare("SELECT count(*) count FROM sqlite_master WHERE type='table' AND name LIKE 'channel_%'").first<{count:number}>();const indexes=await env.DB.prepare("SELECT count(*) count FROM sqlite_master WHERE type='index' AND name LIKE 'idx_channel_%'").first<{count:number}>();const triggers=await env.DB.prepare("SELECT count(*) count FROM sqlite_master WHERE type='trigger' AND name LIKE 'trg_channel_%'").first<{count:number}>();const permissions=await env.DB.prepare("SELECT count(*) count FROM permissions WHERE permission_key LIKE 'channel_%'").first<{count:number}>();expect([tables?.count,indexes?.count,triggers?.count,permissions?.count]).toEqual([7,12,18,10]);expect((await env.DB.prepare("PRAGMA foreign_key_check").all()).results).toEqual([]);});
  it("restores permission immutability and grants no role automatically",async()=>{await applyD1Migrations(env.DB,[...migrations]);expect((await env.DB.prepare("SELECT count(*) count FROM role_permissions rp JOIN permissions p ON p.id=rp.permission_id WHERE p.permission_key LIKE 'channel_%'").first<{count:number}>())?.count).toBe(0);await expect(env.DB.prepare("INSERT INTO permissions(id,permission_key,description,status,created_at,updated_at) VALUES('01a00000-0000-7000-8000-000000009991','channel_runtime:forbidden','Forbidden','active',1,1)").run()).rejects.toThrow(/permission_vocabulary_immutable/);});
  it("rolls back the whole reviewed permission gate on forced failure",async()=>{const prior=migrations.filter(({name})=>!name.includes("0010_channel_adapter_foundation"));await applyD1Migrations(env.DB,[...prior]);const migration=migrations.find(({name})=>name.includes("0010_channel_adapter_foundation"));if(!migration)throw new Error("0010 missing");const restore=migration.queries.findIndex((query)=>query.includes("CREATE TRIGGER trg_permissions_immutable_insert"));expect(restore).toBeGreaterThan(0);const forced:D1Migration={name:"0010_channel_forced_failure.sql",queries:[...migration.queries.slice(0,restore),"INSERT INTO permissions(id,permission_key,description,status,created_at,updated_at) VALUES('01a00000-0000-7000-8000-000000009992','channel_catalog:read','Duplicate','active',1,1)"]};await expect(applyD1Migrations(env.DB,[forced])).rejects.toThrow();expect((await env.DB.prepare("SELECT count(*) count FROM permissions WHERE permission_key LIKE 'channel_%'").first<{count:number}>())?.count).toBe(0);expect((await env.DB.prepare("SELECT count(*) count FROM sqlite_master WHERE type='table' AND name LIKE 'channel_%'").first<{count:number}>())?.count).toBe(0);expect((await env.DB.prepare("SELECT count(*) count FROM sqlite_master WHERE type='trigger' AND name='trg_permissions_immutable_insert'").first<{count:number}>())?.count).toBe(1);expect((await env.DB.prepare("SELECT count(*) count FROM d1_migrations").first<{count:number}>())?.count).toBe(9);});
  it("is replay-safe through the D1 migration ledger",async()=>{await applyD1Migrations(env.DB,[...migrations]);await applyD1Migrations(env.DB,[...migrations]);expect((await env.DB.prepare("SELECT count(*) count FROM d1_migrations").first<{count:number}>())?.count).toBe(10);expect((await env.DB.prepare("SELECT count(*) count FROM channel_catalog").first<{count:number}>())?.count).toBe(4);});
  it("enforces Tenant-aware account, identity, event and evidence foreign keys",async()=>{await applyD1Migrations(env.DB,[...migrations]);for(const table of ["channel_accounts","channel_identity_links","channel_inbound_events","channel_delivery_records","channel_delivery_evidence","channel_response_policies"]){const rows=await env.DB.prepare(`PRAGMA foreign_key_list(${table})`).all();expect(rows.results.length).toBeGreaterThan(0);}});
});
