import { env } from "cloudflare:workers";
import { applyD1Migrations, reset, type D1Migration } from "cloudflare:test";
import { beforeEach, describe, expect, it } from "vitest";
import type { Clock } from "../../src/core/clock";
import type { UuidV7 } from "../../src/core/uuidv7";
import { digestIdentitySubject, type IdentityDigestKeyProvider } from "../../src/persistence/crypto";
import { ChannelAdapterApplication, ChannelAdapterError, DisabledChannelObservationAdapter, DisabledLineResponseRenderer, DisabledLineSignatureVerifier, DisabledTelegramResponseRenderer, DisabledTelegramSignatureVerifier, LocalAllowChannelTraffic, LocalDeterministicSignatureVerifier, LocalWebResponseRenderer, localFixtureSignature, type ChannelObservationPort, type ChannelWorkbenchPort } from "../../src/channel-adapter";

const migrations=env.TEST_MIGRATIONS as readonly D1Migration[];
const ids={tenant:"01a00000-0000-7000-8000-000000002001",user:"01a00000-0000-7000-8000-000000002002",identity:"01a00000-0000-7000-8000-000000002003",membership:"01a00000-0000-7000-8000-000000002004",app:"01a00000-0000-7000-8000-000000002005",tenantB:"01a00000-0000-7000-8000-000000002006",appB:"01a00000-0000-7000-8000-000000002007"};
class TestClock implements Clock { value=2000000; now(){return new Date(this.value);} advance(ms:number){this.value+=ms;} }
let sequence=3000;
class TestIds implements UuidV7 { generate(){sequence+=1;return `01a00000-0000-7000-8000-${String(sequence).padStart(12,"0")}`;} }
class Keys implements IdentityDigestKeyProvider { private readonly key={version:1,secret:new TextEncoder().encode("local-channel-identity-fixture-key")};current(){return this.key;}previous(){return [];} }
const keys=new Keys();
const raw=(data:Record<string,unknown>)=>new TextEncoder().encode(JSON.stringify(data));
async function signed(data:Record<string,unknown>,now:number){const bytes=raw(data);return {rawBody:bytes,signature:await localFixtureSignature(bytes,now)};}
class Workbench implements ChannelWorkbenchPort {calls=0;last:unknown=null;async handle(context:Parameters<ChannelWorkbenchPort["handle"]>[0],input:Parameters<ChannelWorkbenchPort["handle"]>[1]){this.calls+=1;this.last={context,input};if(input.text==="fail")throw new Error("fixture");return Object.freeze({type:input.text==="confirm"?"confirmation" as const:"text" as const,text:input.text==="confirm"?"請確認":"已安全處理",choices:input.text==="confirm"?["確認","取消"]:[],supportCode:null});}}
class Observations implements ChannelObservationPort {events:string[]=[];constructor(private readonly fail=false){}async record(event:Parameters<ChannelObservationPort["record"]>[0]){if(this.fail)throw new Error("sidecar");this.events.push(event.eventType);}}
async function seed(){
  const digest=`v1:${await digestIdentitySubject(keys.current(),"web","local-account-a","local-user-a")}`;
  await env.DB.batch([
    env.DB.prepare("INSERT INTO platform_users(id,status,created_at,updated_at) VALUES(?1,'active',1,1)").bind(ids.user),
    env.DB.prepare("INSERT INTO tenants(id,name,status,created_at,updated_at) VALUES(?1,'Channel Tenant A','active',1,1)").bind(ids.tenant),
    env.DB.prepare("INSERT INTO tenants(id,name,status,created_at,updated_at) VALUES(?1,'Channel Tenant B','active',1,1)").bind(ids.tenantB),
    env.DB.prepare("INSERT INTO identity_mappings(id,platform_user_id,provider,issuer_context,subject_digest,digest_key_version,status,linked_at,created_at,updated_at) VALUES(?1,?2,'local','channel-fixture',?3,1,'active',1,1,1)").bind(ids.identity,ids.user,"1".repeat(64)),
    env.DB.prepare("INSERT INTO tenant_memberships(id,tenant_id,platform_user_id,status,join_source,joined_at,created_at,updated_at) VALUES(?1,?2,?3,'active','test',1,1,1)").bind(ids.membership,ids.tenant,ids.user),
    env.DB.prepare("INSERT INTO applications(id,tenant_id,application_key,name,status,default_locale,version,created_at,updated_at) VALUES(?1,?2,'channel-a','Channel A','active','zh-TW',1,1,1)").bind(ids.app,ids.tenant),
    env.DB.prepare("INSERT INTO applications(id,tenant_id,application_key,name,status,default_locale,version,created_at,updated_at) VALUES(?1,?2,'channel-b','Channel B','active','zh-TW',1,1,1)").bind(ids.appB,ids.tenantB),
    env.DB.prepare("INSERT INTO channel_accounts(channel_account_key,channel_type,tenant_id,application_id,adapter_key,status,signature_policy_version,response_policy_version,version,created_at,updated_at) VALUES('local-account-a','web',?1,?2,'local_web_adapter','enabled_local_only',1,1,1,1,1)").bind(ids.tenant,ids.app),
    env.DB.prepare("INSERT INTO channel_accounts(channel_account_key,channel_type,tenant_id,application_id,adapter_key,status,signature_policy_version,response_policy_version,version,created_at,updated_at) VALUES('line-account-a','line',?1,?2,'disabled_line_adapter','disabled',1,1,1,1,1)").bind(ids.tenant,ids.app),
    env.DB.prepare("INSERT INTO channel_identity_links(id,tenant_id,application_id,channel_account_key,channel_type,external_user_reference_digest,identity_id,membership_id,status,verified_at,version,created_at,updated_at) VALUES('01a00000-0000-7000-8000-000000002101',?1,?2,'local-account-a','web',?3,?4,?5,'linked',1,1,1,1)").bind(ids.tenant,ids.app,digest,ids.identity,ids.membership),
  ]);
}
function make(clock=new TestClock(),workbench=new Workbench(),observation:ChannelObservationPort=new Observations()){return {clock,workbench,app:new ChannelAdapterApplication(env.DB,clock,new TestIds(),keys,[new LocalDeterministicSignatureVerifier(),new DisabledLineSignatureVerifier(),new DisabledTelegramSignatureVerifier()],[new LocalWebResponseRenderer(),new DisabledLineResponseRenderer(),new DisabledTelegramResponseRenderer()],new LocalAllowChannelTraffic(),workbench,observation)};}
const event=(id="evt-1",text="hello",extra:Record<string,unknown>={})=>({externalEventId:id,eventType:"text_message",occurredAt:2000000,externalUserReference:"local-user-a",conversationReference:"conversation-a",deliveryAttempt:1,text,...extra});
beforeEach(async()=>{sequence=3000;await reset();await applyD1Migrations(env.DB,[...migrations]);await seed();});

describe("Channel Adapter Local D1",()=>{
  it("verifies and processes a valid local event through the trusted bridge",async()=>{const {app,workbench}=make(),payload=await signed(event(),2000000);const result=await app.process({channelAccountKey:"local-account-a",...payload,receivedAt:2000000,clientContext:{tenantId:ids.tenantB,verified:true}});expect(result.status).toBe("completed");expect(workbench.calls).toBe(1);expect(JSON.stringify(workbench.last)).not.toContain(ids.tenantB);});
  it("replays an exact duplicate without a second Workbench call",async()=>{const {app,workbench}=make(),payload=await signed(event(),2000000);const first=await app.process({channelAccountKey:"local-account-a",...payload,receivedAt:2000000});const second=await app.process({channelAccountKey:"local-account-a",...payload,receivedAt:2000000});expect(second).toMatchObject({status:"replayed",deliveryRecordId:first.deliveryRecordId});expect(workbench.calls).toBe(1);});
  it("rejects the same external event with a different payload digest",async()=>{const {app}=make(),first=await signed(event(),2000000),second=await signed(event("evt-1","changed"),2000000);await app.process({channelAccountKey:"local-account-a",...first,receivedAt:2000000});await expect(app.process({channelAccountKey:"local-account-a",...second,receivedAt:2000000})).rejects.toMatchObject({code:"CHANNEL_EVENT_CONFLICT"});});
  it.each([[null,"CHANNEL_SIGNATURE_MISSING"],["t=2000000,v1="+"0".repeat(64),"CHANNEL_SIGNATURE_INVALID"]] as const)("fails closed for missing or invalid signatures",async(signature,code)=>{const {app}=make();await expect(app.process({channelAccountKey:"local-account-a",rawBody:raw(event()),signature,receivedAt:2000000})).rejects.toMatchObject({code});expect((await env.DB.prepare("SELECT count(*) count FROM channel_inbound_events").first<{count:number}>())?.count).toBe(0);});
  it("rejects expired signatures before business parsing",async()=>{const {app}=make(),payload=await signed(event(),1000);await expect(app.process({channelAccountKey:"local-account-a",...payload,receivedAt:2000000})).rejects.toMatchObject({code:"CHANNEL_SIGNATURE_EXPIRED"});});
  it("keeps disabled LINE and Telegram verifiers and renderers fail closed",async()=>{const {app}=make();await expect(app.process({channelAccountKey:"line-account-a",rawBody:raw(event()),signature:"anything",receivedAt:2000000})).rejects.toMatchObject({code:"CHANNEL_ADAPTER_DISABLED"});await expect(new DisabledTelegramSignatureVerifier().verify(new Uint8Array([1]),"x",1)).rejects.toMatchObject({code:"CHANNEL_ADAPTER_DISABLED"});await expect(new DisabledTelegramResponseRenderer().render({type:"text",text:"x"},{maxTextLength:1,maxMessages:1,supportsButtons:false,supportsCards:false,supportsReplyToken:false,supportsPush:false,supportsRichMenu:false,localeSupport:["en"]})).rejects.toMatchObject({code:"CHANNEL_ADAPTER_DISABLED"});});
  it("ignores a client verified flag and tenant overrides",async()=>{const {app}=make();await expect(app.process({channelAccountKey:"local-account-a",rawBody:raw({...event(),verified:true,tenantId:ids.tenantB,membershipId:"attacker"}),signature:null,receivedAt:2000000,clientContext:{verified:true}})).rejects.toMatchObject({code:"CHANNEL_SIGNATURE_MISSING"});});
  it.each([["suspended","suspended"],["revoked","revoked"]] as const)("fails closed for %s channel identities",async(status,outcome)=>{await env.DB.prepare("UPDATE channel_identity_links SET status=?1,version=version+1,updated_at=2 WHERE channel_account_key='local-account-a'").bind(status).run();const {app,workbench}=make(),payload=await signed(event(`evt-${status}`),2000000);const result=await app.process({channelAccountKey:"local-account-a",...payload,receivedAt:2000000});expect(result.status).toBe("rejected");expect(workbench.calls).toBe(0);expect((await env.DB.prepare("SELECT identity_resolution_outcome FROM channel_delivery_evidence WHERE delivery_record_id=?1").bind(result.deliveryRecordId).first<{identity_resolution_outcome:string}>())?.identity_resolution_outcome).toBe(outcome);});
  it("returns onboarding-safe output for an unknown identity",async()=>{const {app,workbench}=make(),payload=await signed({...event("evt-unknown"),externalUserReference:"unknown"},2000000);const result=await app.process({channelAccountKey:"local-account-a",...payload,receivedAt:2000000});expect(result).toMatchObject({status:"rejected",response:{responseType:"error"}});expect(workbench.calls).toBe(0);});
  it("does not enter Workbench for unsupported events",async()=>{const {app,workbench}=make(),payload=await signed({...event("evt-unsupported"),eventType:"future_event"},2000000);const result=await app.process({channelAccountKey:"local-account-a",...payload,receivedAt:2000000});expect(result.response.responseType).toBe("unsupported");expect(workbench.calls).toBe(0);});
  it("preserves Workbench confirmation authority",async()=>{const {app}=make(),payload=await signed(event("evt-confirm","confirm"),2000000);expect(await app.process({channelAccountKey:"local-account-a",...payload,receivedAt:2000000})).toMatchObject({response:{responseType:"confirmation"}});});
  it("converts Workbench failure to a safe channel response",async()=>{const {app}=make(),payload=await signed(event("evt-fail","fail"),2000000);expect(await app.process({channelAccountKey:"local-account-a",...payload,receivedAt:2000000})).toMatchObject({status:"completed",response:{responseType:"error"}});});
  it("keeps observability failure isolated from the business result",async()=>{const {app}=make(new TestClock(),new Workbench(),new Observations(true)),payload=await signed(event("evt-sidecar"),2000000);await expect(app.process({channelAccountKey:"local-account-a",...payload,receivedAt:2000000})).resolves.toMatchObject({status:"completed"});});
  it("stores only digests and bounded safe evidence",async()=>{const {app}=make(),payload=await signed({...event("evt-safe"),replyTokenReference:"ephemeral-token",text:"private message"},2000000);await app.process({channelAccountKey:"local-account-a",...payload,receivedAt:2000000});const schema=(await env.DB.prepare("SELECT group_concat(name,' ') names FROM pragma_table_info('channel_inbound_events')").first<{names:string}>())?.names??"";expect(schema).not.toMatch(/reply_token|raw_webhook|message_text|access_token/);const dbText=JSON.stringify((await env.DB.prepare("SELECT * FROM channel_inbound_events").all()).results);expect(dbText).not.toContain("ephemeral-token");expect(dbText).not.toContain("private message");});
  it("keeps delivery evidence immutable and tenant scoped",async()=>{const {app}=make(),payload=await signed(event("evt-evidence"),2000000);const result=await app.process({channelAccountKey:"local-account-a",...payload,receivedAt:2000000});await expect(env.DB.prepare("UPDATE channel_delivery_evidence SET workbench_outcome='changed' WHERE delivery_record_id=?1").bind(result.deliveryRecordId).run()).rejects.toThrow(/immutable/);expect(await app.repository.listDeliveries(ids.tenantB)).toHaveLength(0);});
  it("uses composite indexes for identity, dedup, lease and tenant delivery queries",async()=>{const queries=["EXPLAIN QUERY PLAN SELECT id FROM channel_identity_links WHERE channel_account_key='local-account-a' AND external_user_reference_digest='x' AND status='linked'","EXPLAIN QUERY PLAN SELECT id FROM channel_delivery_records WHERE status='processing' AND lease_expires_at<=1","EXPLAIN QUERY PLAN SELECT delivery_id FROM channel_delivery_evidence WHERE tenant_id=?1 ORDER BY created_at DESC,delivery_id DESC LIMIT 50"];const details=(await Promise.all(queries.map((q)=>env.DB.prepare(q).bind(...(q.includes("?1")?[ids.tenant]:[])).all<{detail:string}>()))).flatMap((r)=>r.results.map((x)=>x.detail)).join(" ");expect(details).toMatch(/idx_channel_identity_digest|sqlite_autoindex_channel_identity_links_3/);expect(details).toContain("idx_channel_delivery_processing_lease");expect(details).toContain("idx_channel_evidence_tenant_date");});
  it("selects one exact processing winner under concurrent claims",async()=>{const {app}=make(),account=await app.repository.getAccount("local-account-a");if(!account)throw new Error("account");const inbound={eventId:"01a00000-0000-7000-8000-000000008001",externalEventId:"evt-race",eventType:"text_message" as const,occurredAt:2000000,receivedAt:2000000,payloadDigest:"a".repeat(64),signatureDigest:"b".repeat(64),deliveryAttempt:1,externalUserReferenceDigest:null,conversationReferenceDigest:null,metadataVersion:1,payloadSize:20};const claims=await Promise.all([app.repository.claim(account,inbound,"01a00000-0000-7000-8000-000000008002","01a00000-0000-7000-8000-000000008003","01a00000-0000-7000-8000-000000008004","race-a",30000),app.repository.claim(account,{...inbound,eventId:"01a00000-0000-7000-8000-000000008005"},"01a00000-0000-7000-8000-000000008006","01a00000-0000-7000-8000-000000008007","01a00000-0000-7000-8000-000000008008","race-b",30000)]);expect(claims.filter((item)=>item.disposition==="execute")).toHaveLength(1);expect(claims.filter((item)=>item.disposition==="processing")).toHaveLength(1);expect((await env.DB.prepare("SELECT count(*) count FROM channel_delivery_records WHERE external_event_id='evt-race'").first<{count:number}>())?.count).toBe(1);});
  it("recovers an abandoned lease with a higher fence and rejects stale completion",async()=>{const {app}=make(),account=await app.repository.getAccount("local-account-a");if(!account)throw new Error("account");const inbound={eventId:"01a00000-0000-7000-8000-000000008101",externalEventId:"evt-fence",eventType:"text_message" as const,occurredAt:2000000,receivedAt:2000000,payloadDigest:"c".repeat(64),signatureDigest:"d".repeat(64),deliveryAttempt:1,externalUserReferenceDigest:null,conversationReferenceDigest:null,metadataVersion:1,payloadSize:20};const first=await app.repository.claim(account,inbound,"01a00000-0000-7000-8000-000000008102","01a00000-0000-7000-8000-000000008103","01a00000-0000-7000-8000-000000008104","fence-a",30000);const takeover=await app.repository.claim(account,{...inbound,receivedAt:2030001,eventId:"01a00000-0000-7000-8000-000000008105"},"01a00000-0000-7000-8000-000000008106","01a00000-0000-7000-8000-000000008107","01a00000-0000-7000-8000-000000008108","fence-b",30000);expect(takeover).toMatchObject({disposition:"execute",record:{fencing_token:2}});const safe={deliveryRecordId:first.record.id,status:"completed" as const,response:{responseType:"text" as const,messages:["safe"],truncated:false,networkUsed:false as const},supportCode:"CH-STALE-FENCE"};await expect(app.repository.complete({record:first.record,leaseOwner:"01a00000-0000-7000-8000-000000008103",status:"completed",safeResult:safe,resultDigest:"e".repeat(64),identityOutcome:"not_required",workbenchOutcome:"SAFE",responseType:"text",inboundEventType:"text_message",deliveryOutcome:"completed",latencyMs:1,supportCode:"CH-STALE-FENCE",evidenceId:"01a00000-0000-7000-8000-000000008109",auditId:"01a00000-0000-7000-8000-000000008110",correlationId:"stale",now:2030002,channelType:"web"})).rejects.toMatchObject({code:"CHANNEL_STALE_COMPLETION"});});
  it("rejects cross-Tenant account and membership relationships in D1",async()=>{await expect(env.DB.prepare("INSERT INTO channel_accounts(channel_account_key,channel_type,tenant_id,application_id,adapter_key,status,signature_policy_version,response_policy_version,version,created_at,updated_at) VALUES('cross-account','web',?1,?2,'local_web_adapter','draft',1,1,1,1,1)").bind(ids.tenant,ids.appB).run()).rejects.toThrow();await expect(env.DB.prepare("UPDATE channel_identity_links SET tenant_id=?1,version=version+1,updated_at=2 WHERE channel_account_key='local-account-a'").bind(ids.tenantB).run()).rejects.toThrow();});
  it("does not pass reply tokens or client authority overrides into Workbench",async()=>{const {app,workbench}=make(),payload=await signed({...event("evt-ephemeral"),replyTokenReference:"reply-secret",tenantId:ids.tenantB,membershipId:"attacker"},2000000);await app.process({channelAccountKey:"local-account-a",...payload,receivedAt:2000000,clientContext:{tenantId:ids.tenantB,membershipId:"attacker"}});expect(JSON.stringify(workbench.last)).not.toMatch(/reply-secret|attacker/);expect(JSON.stringify(workbench.last)).toContain(ids.tenant);});
  it("applies traffic admission before Workbench invocation",async()=>{const workbench=new Workbench(),clock=new TestClock(),app=new ChannelAdapterApplication(env.DB,clock,new TestIds(),keys,[new LocalDeterministicSignatureVerifier()],[new LocalWebResponseRenderer()],{async admit(){return {admitted:false,release:async()=>{}};}},workbench,new DisabledChannelObservationAdapter()),payload=await signed(event("evt-traffic"),2000000);const result=await app.process({channelAccountKey:"local-account-a",...payload,receivedAt:2000000});expect(result.status).toBe("rejected");expect(workbench.calls).toBe(0);});
  it("fails closed when trusted account storage is unavailable",async()=>{const clock=new TestClock(),broken={prepare(){throw new Error("storage");}} as unknown as D1Database,app=new ChannelAdapterApplication(broken,clock,new TestIds(),keys,[new LocalDeterministicSignatureVerifier()],[new LocalWebResponseRenderer()],new LocalAllowChannelTraffic(),new Workbench(),new DisabledChannelObservationAdapter());await expect(app.process({channelAccountKey:"local-account-a",rawBody:raw(event("evt-storage")),signature:"signed",receivedAt:2000000})).rejects.toMatchObject({code:"CHANNEL_STORAGE_FAILED"});});
  it("records one safe Audit and no duplicate domain-side invocation on replay",async()=>{const {app,workbench}=make(),payload=await signed(event("evt-audit"),2000000);await app.process({channelAccountKey:"local-account-a",...payload,receivedAt:2000000});await app.process({channelAccountKey:"local-account-a",...payload,receivedAt:2000000});expect(workbench.calls).toBe(1);expect((await env.DB.prepare("SELECT count(*) count FROM audit_records WHERE action IN ('channel.delivery.claim','channel.delivery.complete') AND resource_type='channel_delivery_record'").first<{count:number}>())?.count).toBe(2);});});

