import { env } from "cloudflare:workers";
import { applyD1Migrations, reset, type D1Migration } from "cloudflare:test";
import { beforeEach, describe, expect, it } from "vitest";
import type { MutationContext } from "../../src/application/core-application-base";
import type { Clock } from "../../src/core/clock";
import type { UuidV7 } from "../../src/core/uuidv7";
import { PlatformTrafficProtectionApplication, trafficPermissions, type TrustedAdmissionContext } from "../../src/platform-traffic";
import type { IdentityDigestKeyProvider } from "../../src/persistence/crypto";

const migrations=env.TEST_MIGRATIONS as readonly D1Migration[];
const tenantA="019d0000-0000-7000-8000-000000000001";
const tenantB="019d0000-0000-7000-8000-000000000002";
const actor=`digest:${"a".repeat(64)}`;
class TestClock implements Clock { value=Date.parse("2027-01-01T00:00:00Z"); now(){return new Date(this.value)} advance(ms:number){this.value+=ms} }
class TestUuid implements UuidV7 { private n=1000; generate(){this.n+=1;return `019d0000-0000-7000-8000-${String(this.n).padStart(12,"0")}`} }
class TestKeys implements IdentityDigestKeyProvider { current(){return {version:1,secret:new TextEncoder().encode("traffic-local-test-key-32-bytes-min")}} previous(){return []} }
let sequence=0;
const mutation=(key?:string):MutationContext=>{sequence+=1;return {idempotencyKey:key??`traffic-key-${sequence}`,actorType:"service",actorReference:actor,correlationId:`traffic-correlation-${sequence}`}};
const fingerprint=(tenantId=tenantA,payload="b".repeat(64))=>({tenantId,applicationScopeKey:"app:one",providerKey:"provider",providerEventId:"event-1",issuerContextDigest:`digest:${"c".repeat(64)}`,normalizedEventType:"event.created",payloadFingerprint:payload});
const admission=(tenantId=tenantA):TrustedAdmissionContext=>({source:"trusted_runtime_context",environment:"development",tenantId,applicationId:"app:one",moduleKey:"event-engine",routeKey:"/internal/webhook",priority:"normal",operationClass:"mutation",actorDigest:actor,ipDigest:`digest:${"d".repeat(64)}`,dependencyKey:null,permissionGranted:true,moduleEnabled:true});
async function seed(){sequence=0;await reset();await applyD1Migrations(env.DB,[...migrations]);await env.DB.batch([env.DB.prepare("INSERT INTO tenants (id,name,status,created_at,updated_at) VALUES (?1,?2,'active',1,1)").bind(tenantA,"Tenant A"),env.DB.prepare("INSERT INTO tenants (id,name,status,created_at,updated_at) VALUES (?1,?2,'active',1,1)").bind(tenantB,"Tenant B")])}
function harness(){const clock=new TestClock();return {clock,app:new PlatformTrafficProtectionApplication(env.DB,clock,new TestUuid(),new TestKeys())}}

beforeEach(seed);

describe("Platform Traffic Protection Local D1",()=>{
 it("installs exact schema inventory and tenant foreign keys",async()=>{const tables=await env.DB.prepare("SELECT count(*) count FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' AND name NOT IN ('d1_migrations','_cf_METADATA')").first<{count:number}>();const indexes=await env.DB.prepare("SELECT count(*) count FROM sqlite_master WHERE type='index' AND name NOT LIKE 'sqlite_autoindex_%'").first<{count:number}>();const triggers=await env.DB.prepare("SELECT count(*) count FROM sqlite_master WHERE type='trigger'").first<{count:number}>();expect([tables?.count,indexes?.count,triggers?.count]).toEqual([42,87,58]);expect((await env.DB.prepare("PRAGMA foreign_key_check").all()).results).toEqual([])});
 it("registers exact traffic permissions and keeps vocabulary immutable",async()=>{const rows=await env.DB.prepare("SELECT permission_key FROM permissions WHERE permission_key LIKE 'traffic:%' OR permission_key LIKE 'circuit:%' OR permission_key LIKE 'degradation:%' ORDER BY permission_key").all<{permission_key:string}>();expect(rows.results.map(x=>x.permission_key)).toEqual(Object.values(trafficPermissions).sort());await expect(env.DB.prepare("INSERT INTO permissions(id,permission_key,description,status,created_at,updated_at) VALUES('019d0000-0000-7000-8000-000000009999','traffic:runtime','bad','active',1,1)").run()).rejects.toThrow(/permission_vocabulary_immutable/)});
 it("claims, completes, and replays one stored webhook result",async()=>{const {app}=harness();const first=await app.claimWebhook(fingerprint(),mutation());await app.completeWebhook(tenantA,first.receiptId,{code:"COMPLETED"},mutation());const replay=await app.claimWebhook(fingerprint(),mutation());expect(replay).toMatchObject({status:"duplicate_replay",executeMutation:false,safeResult:{code:"COMPLETED"}});expect((await env.DB.prepare("SELECT count(*) count FROM webhook_receipts").first<{count:number}>())?.count).toBe(1)});
 it("rejects same provider identity with a different payload",async()=>{const {app}=harness();await app.claimWebhook(fingerprint(),mutation());await expect(app.claimWebhook(fingerprint(tenantA,"e".repeat(64)),mutation())).rejects.toMatchObject({code:"EVENT_FINGERPRINT_CONFLICT"})});
 it("atomically expires an old receipt and creates a new dedup winner",async()=>{const {app,clock}=harness();const first=await app.claimWebhook(fingerprint(),mutation("first-window"));clock.advance(24*60*60*1000+1);const second=await app.claimWebhook(fingerprint(),mutation("second-window"));expect(second.receiptId).not.toBe(first.receiptId);const statuses=await env.DB.prepare("SELECT status FROM webhook_receipts ORDER BY created_at,id").all<{status:string}>();expect(statuses.results.map(x=>x.status).sort()).toEqual(["expired","processing"])});
 it("records bounded evidence with audit and idempotent replay",async()=>{const {app}=harness();const m=mutation("evidence-key");const decision={admitted:false,observedOnly:false,retryAfterSeconds:5,reasonCode:"RATE_LIMITED" as const};const first=await app.recordRateLimitEvidence(admission(),decision,m);const replay=await app.recordRateLimitEvidence(admission(),decision,m);expect(replay).toEqual(first);expect((await env.DB.prepare("SELECT count(*) count FROM rate_limit_evidence").first<{count:number}>())?.count).toBe(1);expect((await env.DB.prepare("SELECT count(*) count FROM audit_records WHERE action='traffic.rate_limit.evidence'").first<{count:number}>())?.count).toBe(1)});
 it("enforces tenant evidence isolation and platform permission",async()=>{const {app}=harness();const decision={admitted:false,observedOnly:false,retryAfterSeconds:5,reasonCode:"RATE_LIMITED" as const};await app.recordRateLimitEvidence(admission(tenantA),decision,mutation());await app.recordRateLimitEvidence(admission(tenantB),decision,mutation());expect((await app.listEvidence(tenantA,{tenantId:tenantA,permissionKeys:[trafficPermissions.readTenant]})).items).toHaveLength(1);await expect(app.listEvidence(tenantB,{tenantId:tenantA,permissionKeys:[trafficPermissions.readTenant]})).rejects.toThrow();expect((await app.listEvidence(null,{tenantId:null,permissionKeys:[trafficPermissions.readPlatform]})).items).toHaveLength(2)});
 it("uses bounded index-backed evidence and retention queries",async()=>{const plans=await Promise.all([env.DB.prepare("EXPLAIN QUERY PLAN SELECT id FROM rate_limit_evidence WHERE tenant_id=?1 ORDER BY window_started_at DESC,id LIMIT 50").bind(tenantA).all<{detail:string}>(),env.DB.prepare("EXPLAIN QUERY PLAN SELECT id FROM webhook_receipts WHERE tenant_id=?1 AND expires_at<=?2 ORDER BY expires_at,id LIMIT 50").bind(tenantA,99).all<{detail:string}>()]);const text=plans.flatMap(p=>p.results.map(x=>x.detail)).join("\n");expect(text).toContain("idx_rate_limit_tenant_window");expect(text).toContain("idx_webhook_tenant_expiry")});
 it("prevents mutation or deletion of immutable evidence",async()=>{const {app}=harness();await app.recordRateLimitEvidence(admission(),{admitted:false,observedOnly:false,retryAfterSeconds:5,reasonCode:"RATE_LIMITED"},mutation());await app.claimWebhook(fingerprint(),mutation());await expect(env.DB.prepare("UPDATE rate_limit_evidence SET reason_code='changed'").run()).rejects.toThrow(/rate_limit_evidence_immutable/);await expect(env.DB.prepare("DELETE FROM webhook_receipts").run()).rejects.toThrow(/webhook_receipt_immutable/)});
});

describe("Traffic permission registration failure safety",()=>{
 it("rolls back 0005 permission insert and trigger removal on forced failure",async()=>{await reset();const prior=migrations.filter(m=>!m.name.includes("0005_platform_traffic_protection"));await applyD1Migrations(env.DB,[...prior]);const migration=migrations.find(m=>m.name.includes("0005_platform_traffic_protection"));if(!migration)throw new Error("0005 missing");const restore=migration.queries.findIndex(q=>q.includes("CREATE TRIGGER trg_permissions_immutable_insert"));expect(restore).toBeGreaterThan(0);const failing:D1Migration={name:"0005_forced_failure.sql",queries:[...migration.queries.slice(0,restore),"INSERT INTO permissions(id,permission_key,description,status,created_at,updated_at) VALUES('019d0000-0000-7000-8000-000000009998','traffic:read_tenant','duplicate','active',1,1)"]};await expect(applyD1Migrations(env.DB,[failing])).rejects.toThrow();expect((await env.DB.prepare("SELECT count(*) count FROM permissions WHERE permission_key LIKE 'traffic:%' OR permission_key LIKE 'circuit:%' OR permission_key LIKE 'degradation:%'").first<{count:number}>())?.count).toBe(0);expect((await env.DB.prepare("SELECT count(*) count FROM sqlite_master WHERE type='trigger' AND name='trg_permissions_immutable_insert'").first<{count:number}>())?.count).toBe(1);expect((await env.DB.prepare("SELECT count(*) count FROM d1_migrations").first<{count:number}>())?.count).toBe(4)});
});